export const NOTIFICATION_PENDING = "PENDING" as const;
export const NOTIFICATION_APPROVED = "APPROVED" as const;
export const NOTIFICATION_REJECTED = "REJECTED" as const;
export const NOTIFICATION_CHANGES_REQUESTED = "CHANGES_REQUESTED" as const;
export const NOTIFICATION_ADMIN_APPROVAL_REQUIRED =
  "ADMIN_APPROVAL_REQUIRED" as const;
export const NOTIFICATION_TEAM_LEAD_APPROVAL_REQUIRED =
  "TEAM_LEAD_APPROVAL_REQUIRED" as const;
export const NOTIFICATION_COMPLETED = "COMPLETED" as const;

export const NOTIFICATION_STATUSES = [
  NOTIFICATION_PENDING,
  NOTIFICATION_APPROVED,
  NOTIFICATION_REJECTED,
  NOTIFICATION_CHANGES_REQUESTED,
  NOTIFICATION_ADMIN_APPROVAL_REQUIRED,
  NOTIFICATION_TEAM_LEAD_APPROVAL_REQUIRED,
  NOTIFICATION_COMPLETED,
] as const;

export type NotificationStatus = (typeof NOTIFICATION_STATUSES)[number];

export const NOTIFICATION_STATUS_LABELS: Record<NotificationStatus, string> = {
  PENDING: "Pending",
  APPROVED: "Approved",
  REJECTED: "Rejected",
  CHANGES_REQUESTED: "Changes Requested",
  ADMIN_APPROVAL_REQUIRED: "Admin Approval Required",
  TEAM_LEAD_APPROVAL_REQUIRED: "Team Lead Approval Required",
  COMPLETED: "Completed",
};
